#ifndef RENDERING_CONSTANTS_H
#define RENDERING_CONSTANTS_H


const m_Vec3 R_FIRE_LIGHT_COLOR( 1.4f, 1.2f, 0.8f );
const m_Vec3 R_SUN_LIGHT_COLOR( 0.95f, 0.95f, 1.0f  );
const m_Vec3 R_AMBIENT_LIGHT_COLOR( 0.06f, 0.06f, 0.06f );


#endif//RENDERING_CONSTANTS_H
